Pattern Library additions
shiftsave/anni-platform pull request #18
Opened 2017-04-04 17:28 UTC by shiftsave

This PR implements some base components and their styling, list to follow.

2017-04-05 20:13 UTC, hudakdidit commented on src/routes/patterns/components/Alerts.js
> +  showDefault = () => {
Why not just `() {`

2017-04-05 20:18 UTC, jonathanhudak requested changes
Hey left some feedback. I have some local work I'll push up in the next few days as a PR.

2017-04-05 20:18 UTC, hudakdidit commented on src/routes/patterns/components/Alerts.js
> +  showDefault = () => {
Why not just `() {`

2017-04-05 20:18 UTC, hudakdidit commented on src/routes/patterns/components/Alerts.js
> +        {isDefault &&
There is a fair amount of duplication in each of these cases. I would suggest refactoring to simplify. You could utilize state-less components that just take props to help reduce the repetition. Happy to help if needed.

2017-04-05 20:18 UTC, hudakdidit commented on src/routes/patterns/components/Alerts.js
> +                {' '}
`&nbsp;`?

2017-04-05 20:18 UTC, hudakdidit commented on src/styles/global/mixins.styl
> +pxTo($px, $unit)
Let's just use `px` ;-)

http://html5weekly.us1.list-manage.com/track/click?u=0618f6a79d6bb9675f313ceb2&id=73725a8931&e=4df4fd938a

2017-04-14 21:37 UTC, shiftsave commented on src/routes/patterns/components/Alerts.js
> +  showDefault = () => {
Super rough all around I'm gonna go ahead and trim this PR significantly! just wanted to get some starter files here!

2017-04-14 21:38 UTC, shiftsave commented on src/routes/patterns/components/Alerts.js
> +        {isDefault &&
totally, gonna rework all of this, just wanted a starting point

2017-04-14 21:39 UTC, shiftsave commented on src/styles/global/mixins.styl
> +pxTo($px, $unit)
Ah the religion of em vs rem vs px, em-based mqs make more sense tho and rem keep it more consistent. This is not really a pain if we use a pxtorem function like the one I have in there. Check this other article out - https://zellwk.com/blog/media-query-units/

2017-04-20 04:31 UTC, hudakdidit commented on src/styles/global/mixins.styl
> +pxTo($px, $unit)
I'm down for em media queries and rem padding/margin font-size.

2017-04-20 04:32 UTC, merged