Full-screen Project View
shiftsave/anni-platform pull request #43
Opened 2017-06-30 21:10 UTC by shiftsave

This PR implements styles for full-screen navigation mode for Project Details. Note that no functionality for drag-n-drop or rearrangement of sections is in scope for this PR.

References: #36 

#### Preview
##### Headline
![image](https://user-images.githubusercontent.com/1121873/27754116-b496a378-5d9d-11e7-8f93-8ed4c32ec9e5.png)

##### Editor
![image](https://user-images.githubusercontent.com/1121873/27754119-b9a50c42-5d9d-11e7-9469-4931358d0a22.png)

##### Moodboard
![image](https://user-images.githubusercontent.com/1121873/27754124-c11cad36-5d9d-11e7-97b2-2e7d3c64bcd2.png)

##### Storyboards
![image](https://user-images.githubusercontent.com/1121873/27754133-cdbf4684-5d9d-11e7-8e24-12c868554d98.png)

2017-06-30 21:27 UTC, jonathanhudak requested changes

2017-06-30 21:27 UTC, hudakdidit commented on src/routes/project/components/Details.js
>        showStyleframes: false
Instead of tracking all of these individually, perhaps we could just store an active section index? We could significantly reduce the complexity.

2017-06-30 21:27 UTC, hudakdidit commented on src/routes/project/components/Details.js
> +        </ProjectControls>
could replace this with a map of sections.

```
const sections = [{ name: "Storyboards"}, ...]
sections.map((section, index) => <Section name={section.name} checked={index === this.activeSectionIndex} onClick={this.toggleSection} />);

toggleSection = activeSectionIndex=> this.setState({ activeSectionIndex });
```

2017-07-01 22:35 UTC, hudakdidit commented
@shiftsave just pushed a refactor update. I'll work on the reordering behavior and order persistence in the db next.

2017-07-01 22:36 UTC, hudakdidit commented
Oh i see reordering is not in scope for this PR. We should probably just get this dialed in for mobile and then check it in after testing. I can open a new PR then for the reorderin behavior.

2017-07-01 22:42 UTC, shiftsave commented
@hudakdidit Yeah let's try to merge asap and open a new PR from here!

2017-07-02 04:40 UTC, jonathanhudak approved these changes

2017-07-02 17:03 UTC, hudakdidit commented
@shiftsave just pushed a commit so that switching sections updates the url. This enables you to link to a particular section. What is the plan for mobile?

2017-07-02 17:43 UTC, hudakdidit commented
That last commit hides the labels of the section navigation for smaller thresholds. I tested on my phone and this seems to alleviate some of the issue. We should open a new PR to flesh out the interaction better for this. I could see some kind of slide out behavior, which could give you the ability to reorder etc.

2017-07-02 17:43 UTC, hudakdidit commented
I'd say we should check this in at this point.

2017-07-02 18:48 UTC, shiftsave commented
I agree! I also have a commit for hiding the labels haha. Lets just roll
with yours as I forgot to push mine last night.
On Sun, Jul 2, 2017 at 10:43 AM Jonathan Hudak <notifications@github.com>
wrote:

> I'd say we should check this in at this point.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/anni-platform/anni-platform/pull/43#issuecomment-312506100>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABEeUWRFvUqgAmnbirVQ5ZpleIVe4CHmks5sJ9bYgaJpZM4OLDhP>
> .
>

2017-07-02 22:01 UTC, merged